<a href="https://colab.research.google.com/github/St2Day/projeto-bd-colab/blob/main/Untitled1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sqlite3
import pandas as pd
from IPython.display import display

# Conectar ao banco de dados (em memória)
conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

# Garantir que as chaves estrangeiras estejam ativas
cursor.execute("PRAGMA foreign_keys = ON;")

print("Conexão com o banco de dados estabelecida com sucesso!")

# Tabela Pessoas
cursor.execute('''
    CREATE TABLE IF NOT EXISTS pessoas (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        nome TEXT NOT NULL,
        idade INTEGER
    );
''')

# Tabela Produtos
cursor.execute('''
    CREATE TABLE IF NOT EXISTS produtos (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        descricao TEXT NOT NULL,
        estoque INTEGER,
        preco REAL
    );
''')

# Tabela Vendas (com chaves estrangeiras)
cursor.execute('''
    CREATE TABLE IF NOT EXISTS vendas (
        id_venda INTEGER PRIMARY KEY AUTOINCREMENT,
        id_pessoa INTEGER,
        id_produto INTEGER,
        quantidade INTEGER,
        FOREIGN KEY (id_pessoa) REFERENCES pessoas(id),
        FOREIGN KEY (id_produto) REFERENCES produtos(id)
    );
''')

conn.commit()
print("Tabelas criadas com sucesso!")

# Inserir pessoas
pessoas = [
    ('Maria', 30),
    ('João', 25),
    ('Ana', 40),
    ('Carlos', 35),
    ('Beatriz', 28)
]

cursor.executemany("INSERT INTO pessoas (nome, idade) VALUES (?, ?)", pessoas)

# Inserir produtos
produtos = [
    ('Caneta', 100, 1.50),
    ('Caderno', 50, 6.50),
    ('Lápis', 200, 0.75),
    ('Borracha', 80, 1.20),
    ('Apontador', 60, 2.00)
]

cursor.executemany("INSERT INTO produtos (descricao, estoque, preco) VALUES (?, ?, ?)", produtos)

conn.commit()
print("Dados inseridos com sucesso!")

# Consultar pessoas
cursor.execute("SELECT * FROM pessoas")
pessoas_df = pd.DataFrame(cursor.fetchall(), columns=['id', 'nome', 'idade'])
print("Tabela Pessoas:")
display(pessoas_df)

# Consultar produtos
cursor.execute("SELECT * FROM produtos")
produtos_df = pd.DataFrame(cursor.fetchall(), columns=['id', 'descricao', 'estoque', 'preco'])
print("Tabela Produtos:")
display(produtos_df)

# Inserir vendas
vendas = [
    (1, 1, 10),  # Maria comprou 10 canetas
    (2, 2, 2),   # João comprou 2 cadernos
    (3, 3, 5),   # Ana comprou 5 lápis
    (1, 4, 3),   # Maria comprou 3 borrachas
    (4, 5, 2)    # Carlos comprou 2 apontadores
]

cursor.executemany("INSERT INTO vendas (id_pessoa, id_produto, quantidade) VALUES (?, ?, ?)", vendas)
conn.commit()
print("Vendas registradas com sucesso!")

# Consultar vendas
cursor.execute("SELECT * FROM vendas")
vendas_df = pd.DataFrame(cursor.fetchall(), columns=['id_venda', 'id_pessoa', 'id_produto', 'quantidade'])
print("Tabela Vendas:")
display(vendas_df)

# Consulta JOIN para mostrar detalhes das vendas
cursor.execute('''
    SELECT v.id_venda, p.nome, pr.descricao, v.quantidade, pr.preco, (v.quantidade * pr.preco) as valor_total
    FROM vendas v
    JOIN pessoas p ON v.id_pessoa = p.id
    JOIN produtos pr ON v.id_produto = pr.id
    ORDER BY v.id_venda;
''')

vendas_detalhadas = pd.DataFrame(cursor.fetchall(),
                                columns=['ID Venda', 'Cliente', 'Produto', 'Quantidade', 'Preço Unitário', 'Valor Total'])
print("Detalhes das Vendas:")
display(vendas_detalhadas)

# Total de vendas por cliente
cursor.execute('''
    SELECT p.nome, COUNT(v.id_venda) as total_compras, SUM(v.quantidade * pr.preco) as valor_total
    FROM vendas v
    JOIN pessoas p ON v.id_pessoa = p.id
    JOIN produtos pr ON v.id_produto = pr.id
    GROUP BY p.nome
    ORDER BY valor_total DESC;
''')

vendas_por_cliente = pd.DataFrame(cursor.fetchall(),
                                 columns=['Cliente', 'Total de Compras', 'Valor Total'])
print("Total de Vendas por Cliente:")
display(vendas_por_cliente)

# Produtos mais vendidos
cursor.execute('''
    SELECT pr.descricao, SUM(v.quantidade) as quantidade_vendida, SUM(v.quantidade * pr.preco) as valor_total
    FROM vendas v
    JOIN produtos pr ON v.id_produto = pr.id
    GROUP BY pr.descricao
    ORDER BY quantidade_vendida DESC;
''')

produtos_mais_vendidos = pd.DataFrame(cursor.fetchall(),
                                     columns=['Produto', 'Quantidade Vendida', 'Valor Total'])
print("Produtos Mais Vendidos:")
display(produtos_mais_vendidos)

import matplotlib.pyplot as plt

# Configurar o estilo do gráfico
plt.style.use('ggplot')
plt.figure(figsize=(10, 6))

# Criar gráfico de barras
plt.bar(produtos_mais_vendidos['Produto'], produtos_mais_vendidos['Quantidade Vendida'], color='skyblue')
plt.title('Quantidade Vendida por Produto', fontsize=15)
plt.xlabel('Produto', fontsize=12)
plt.ylabel('Quantidade Vendida', fontsize=12)
plt.xticks(rotation=45)
plt.tight_layout()

# Exibir o gráfico
plt.show()

# Função para inserir um novo produto com tratamento de erros
def inserir_produto(descricao, estoque, preco):
    try:
        cursor.execute("INSERT INTO produtos (descricao, estoque, preco) VALUES (?, ?, ?)",
                      (descricao, estoque, preco))
        conn.commit()
        print(f"Produto '{descricao}' inserido com sucesso!")
        return True
    except sqlite3.Error as erro:
        print(f"Erro ao inserir produto: {erro}")
        conn.rollback()
        return False

# Testando a função
inserir_produto("Régua", 45, 3.25)

# Verificando se o produto foi inserido
cursor.execute("SELECT * FROM produtos WHERE descricao = 'Régua'")
resultado = cursor.fetchone()
if resultado:
    print(f"Produto encontrado: ID={resultado[0]}, Descrição={resultado[1]}, Estoque={resultado[2]}, Preço={resultado[3]}")
else:
    print("Produto não encontrado.")

    # Fechar a conexão
conn.close()
print("Conexão com o banco de dados encerrada.")